const ActionsConstants = {
    // Reducer
    SIGN_OUT_STORE: 'SIGN_OUT_STORE',
    SET_USERNAME: 'SET_USERNAME',
    HANDLE_SIGN_IN_RESPONSE: 'HANDLE_SIGN_IN_RESPONSE',
    HANDLE_USER_EXISTS_RESPONSE: 'HANDLE_USER_EXISTS_RESPONSE',
    HANDLE_USER_DETAILS_RESPONSE: 'HANDLE_USER_DETAILS_RESPONSE',
    UPDATE_PROFILE_DETAILS: 'UPDATE_PROFILE_DETAILS',
    HANDLE_SEARCH_USERS_RESPONSE: 'HANDLE_SEARCH_USERS_RESPONSE',
    HANDLE_SEARCH_RESTAURANTS_RESPONSE: 'HANDLE_SEARCH_RESTAURANTS_RESPONSE',
    UPDATE_RESTAURANTS_GRADE: 'UPDATE_RESTAURANTS_GRADE',
    HANDLE_GET_RESTAURANTS_RESPONSE: 'HANDLE_GET_RESTAURANTS_RESPONSE',
    HANDLE_RESTAURANT_DETAILS_RESPONSE: 'HANDLE_RESTAURANT_DETAILS_RESPONSE',
    HANDLE_GET_REVIEW_RESPONSE: 'HANDLE_GET_REVIEW_RESPONSE',
    UPDATE_REVIEW_CRITERIA: 'UPDATE_REVIEW_CRITERIA',
    DELETE_REVIEW_FROM_PROFILE: 'DELETE_REVIEW_FROM_PROFILE',

    // Saga
    SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
    USER_EXISTS_REQUEST: 'USER_EXISTS_REQUEST',
    IS_LOGGED_IN_REQUEST: 'IS_LOGGED_IN_REQUEST',
    USER_DETAILS_REQUEST: 'USER_DETAILS_REQUEST',
    UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    SEARCH_USERS_REQUEST: 'SEARCH_USERS_REQUEST',
    SEARCH_RESTAURANTS_REQUEST: 'SEARCH_RESTAURANTS_REQUEST',
    GET_RESTAURANTS_REQUEST: 'GET_RESTAURANTS_REQUEST',
    RESTAURANT_DETAILS_REQUEST: 'RESTAURANT_DETAILS_REQUEST',
    ADD_REVIEW_REQUEST: 'ADD_REVIEW_REQUEST',
    EDIT_REVIEW_REQUEST: 'EDIT_REVIEW_REQUEST',
    GET_REVIEW_REQUEST: 'GET_REVIEW_REQUEST',
    DELETE_REVIEW: 'DELETE_REVIEW',

};

export {ActionsConstants}
